codecov:
  notify:
    require_ci_to_pass: true

comment:
  behavior: default
  layout: header, diff, tree
  require_changes: false

coverage:
  precision: 2
  range: "75..95"
  round: nearest
  status:
    project:
      default:
        threshold: 5

  ignore:
  - build
  - .*/src/test/.*

